In [3]:
import torch
import torch.nn.functional as F

In [13]:
def softmax(x):
    """This operators on a sequence of data"""
    exps = torch.exp(x)
    return exps / exps.sum()

x = torch.tensor([
    [2.0, 1.0, 0.0],
    [1.0, 3.0, 2.0],
])

print(torch.sum(softmax(x)))
print(torch.vmap(sum)(torch.vmap(softmax)(x)))


tensor(1.)
tensor([1.0000, 1.0000])


In [20]:
#vmap over column

original = print(torch.vmap(softmax, in_dims=1, out_dims=1)(x))

tensor([[0.7311, 0.1192, 0.1192],
        [0.2689, 0.8808, 0.8808]])


In [21]:
# vmap over column and spit out answer along row

reverse = print(torch.vmap(softmax, in_dims=1, out_dims=0)(x))

tensor([[0.7311, 0.2689],
        [0.1192, 0.8808],
        [0.1192, 0.8808]])


In [22]:
reverse.T == original

AttributeError: 'NoneType' object has no attribute 'T'