In [ ]:
import torch

def cross_entropy(y, y_pred):
    """cross entropy loss is used to measure how far off your models probabilities are from the truth values."""
    return - (y * torch.log(y_pred) + (1- y) * torch.log( 1 - y_pred))


y_target = torch.Tensor([0, 1, 0])
y_pred = torch.Tensor([0.1, 0.8, 0.1])
cross_entropy(y_target, y_pred)

tensor([0.1054, 0.2231, 0.1054])

In [3]:
import torch

torch.randint(0, 10, (4, 2)).shape

torch.Size([4, 2])

In [13]:
start_indices = torch.randint(0, 100, (4, )) # return 32, 1

start_indices[:, None] + torch.arange(100) == start_indices[:, None] + torch.arange(100)[None, :]

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, 

In [18]:
torch.softmax(torch.rand(32, 128), dim=1)

tensor([[0.0096, 0.0070, 0.0107,  ..., 0.0078, 0.0068, 0.0059],
        [0.0094, 0.0078, 0.0049,  ..., 0.0082, 0.0083, 0.0093],
        [0.0105, 0.0061, 0.0053,  ..., 0.0077, 0.0101, 0.0088],
        ...,
        [0.0104, 0.0047, 0.0114,  ..., 0.0059, 0.0076, 0.0109],
        [0.0050, 0.0100, 0.0121,  ..., 0.0089, 0.0117, 0.0071],
        [0.0110, 0.0072, 0.0073,  ..., 0.0081, 0.0125, 0.0048]])