In [3]:
import torch
import torch.nn.functional as F

In [13]:
def softmax(x):
    """This operators on a sequence of data"""
    exps = torch.exp(x)
    return exps / exps.sum()

x = torch.tensor([
    [2.0, 1.0, 0.0],
    [1.0, 3.0, 2.0],
])

print(torch.sum(softmax(x)))
print(torch.vmap(sum)(torch.vmap(softmax)(x)))


tensor(1.)
tensor([1.0000, 1.0000])


In [28]:
#vmap over column

original = torch.vmap(softmax, in_dims=1, out_dims=1)(x)
original

tensor([[0.7311, 0.1192, 0.1192],
        [0.2689, 0.8808, 0.8808]])

In [29]:
# vmap over column and spit out answer along row

reverse = torch.vmap(softmax, in_dims=1, out_dims=0)(x)
reverse

tensor([[0.7311, 0.2689],
        [0.1192, 0.8808],
        [0.1192, 0.8808]])

In [35]:
torch.all(reverse.T == original)

tensor(True)

In [38]:
# softmax extreme example

base = torch.tensor([1.0, 2.0, 3.0])

for scale in [1, 2, 5, 10]:
    logits = scale * base


    print(logits)
    print(softmax(logits))

tensor([1., 2., 3.])
tensor([0.0900, 0.2447, 0.6652])
tensor([2., 4., 6.])
tensor([0.0159, 0.1173, 0.8668])
tensor([ 5., 10., 15.])
tensor([4.5094e-05, 6.6925e-03, 9.9326e-01])
tensor([10., 20., 30.])
tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])
